name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff build

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Build sdist/wheel (for sanity)
        run: |
          python -m build || echo "no pyproject / setup; build skipped"

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-artifacts
          path: |
            **/*.py
            README.md
            LICENSE
            .github/workflows/ci.yml
